[project]
name = "dfgdgffdg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cachetools>=6.1.0",
    "fastapi[all]>=0.116.1",
    "httpx>=0.28.1",
]
